version: '3.8'
services:
  app:
    build:
      args:
        ARG_LINUX_LOCALE: en_US.UTF-8
        ARG_RUBY_VERSION: 3.1.2
        ARG_NODE_VERSION: 18.4.0
      context: .
    depends_on:
      - postgresql
      - redis
    working_dir: /home/user/vaga-dev-sr
    environment:
      BINDING: 0.0.0.0
      PORT: 3000
      DATABASE_URL: postgres://user:password@postgresql:5432
      REDIS_URL: redis://:@redis:6379
    env_file: .env.docker-compose
    extra_hosts:
      - dockerhost:host-gateway
    ports:
      - 3000:3000
    tty: true
    volumes:
      - app_local:/usr/local
      - ~/.ssh:/home/user/.ssh
      - ~/.gitconfig:/home/user/.gitconfig
      - ~/.bash_history:/home/user/.bash_history
      - .:/home/user/vaga-dev-sr
  postgresql:
    image: postgres:14.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2
volumes:
  app_local:
  postgresql_data:
